### ISSUE TITLE
Possible incompatibility with Playwright?

### ISSUE THREAD

**Issue by kirkpams** [center-key/w3c-html-validator#10]
I'm trying to use this validator with the Playwright testing framework. I've just done clean installs (version information below) and tried to run a basic test case. Here is the code for the test case:

```
import { w3cHtmlValidator } from 'w3c-html-validator';
import { test } from '@playwright/test';

const URL = "/path/to/local/index.html";

test("Validation check", async () => {
  const options = { filename: URL };
  w3cHtmlValidator.validate(options).then(console.log);
});
```

Whenever I run Playwright, I get the following error:

```
$ npx playwright test
Error: No "exports" main defined in /Users/.../node_modules/w3c-html-validator/package.json

   at example.spec.ts:1

> 1 | import { w3cHtmlValidator } from 'w3c-html-validator';
    | ^
  2 | import { test } from '@playwright/test';
  3 |
  4 | const URL = "/path/to/local/index.html";

    at Object.<anonymous> (/Users/.../tests/example.spec.ts:1:1)

Error: No tests found
```

Here's the relevant version information:

```
$ node --version
v20.3.0
$ npm --version
9.6.7
$ npm info playwright
playwright@1.36.2 | Apache-2.0 | deps: 1 | versions: 3902
...
$ npm info w3c-html-validator
w3c-html-validator@1.4.0 | MIT | deps: 5 | versions: 32
```

Is this validator just incompatible with Playwright, or is there a fix for this?

**Comment by pilafmon** [comment]
I've never used **Playwrite,** but I assume it supports ES Modules.

**w3c-html-validator** is an ESM package.  **node** has a collection of rules based on `package.json` settings and file extensions to determine when to use ESM mode.  Something in your environment looks to be causing **node** to use the old CommonJS mode instead of ESM mode.

Check your `package.json` file to see if you have ESM enabled:
```json
"type": "module",
```

More information is at:
https://nodejs.org/api/packages.html#determining-module-system

To run a little test yourself you can do the following:
```shell
mkdir my-proj
cd my-proj
npm init --yes
npm install w3c-html-validator
```
Edit the `package.json` file to add: `"type": "module",`

Create a file named `index.js`:
```js
import { w3cHtmlValidator } from 'w3c-html-validator';

console.log(w3cHtmlValidator.version);
w3cHtmlValidator
   .validate({ website: 'https://pretty-print-json.js.org/' })
   .then(w3cHtmlValidator.reporter);
```

Then execute the command: `node index.js`

**Comment by kirkpams** [comment]
That was it. Thanks!
