### ISSUE TITLE
Ignoring multiple error messages

### ISSUE THREAD

**Issue by pepelsbey** [center-key/w3c-html-validator#11]
Hello! I’m glad I found your validator: it’s simple enough for my needs compared to the original vnu one. One of the reasons to start looking for another tool was the vnu’s problems with filtering out error messages. It’s just unreliable: some work fine, some just don’t. But in your case, it seems to be working exceptionally well :)

Unfortunately, I need to filter out multiple error messages, and it’s unclear from the readme how to achieve that or if it’s even possible. I tried using multiple `--ignore` keys or combining strings into a single one, no luck so far.

The best solution would be to support a simple config file with exceptions, [like vnu does](https://github.com/validator/validator#--filterfile-filename):

> **--filterfile FILENAME**
>
> Specifies a filename. Each line of the file contains either a regular
expression or starts with “#” to indicate the line is a comment. Any error
message or warning message that matches a regular expression in the file is
filtered out (dropped/suppressed).

I hope you can clarify this in the readme or consider supporting an ignore file. Thank you!

**Comment by pilafmon** [comment]
Multiple validation messages can be skipped using a regex with _"or"_ operators in the `--exclude` flag.

For example, the command:
```script
html-validator docs '--ignore=/^Duplicate ID|^Section lacks|^Element .blockquote. not allowed/'
```
will ignore the following 3 types of validation messages:

1. _Duplicate ID "[name]"_
2. _Section lacks heading. Consider using “h2”-“h6” elements to add identifying headings to all sections, or else use a “div” element instead for any cases where no heading is needed._
3. _Element “blockquote” not allowed as child of element “span” in this context. (Suppressing further errors from this subtree.)_

Because of the spaces in the search text, be sure to wrap the entire `--ignore` flag plus its value in quotes.

**Comment by pepelsbey** [comment]
Oh, good to know! It's definitely something worth adding to the readme. But the convenience and readability/maintainability of that kind of filtering is questionable 😅 I hope you'd consider supporting an ignore file. Thanks!

**Comment by pilafmon** [comment]
The proposed solution is to supplement the current `--ignore` flag with a new `--ignore-config` flag.

See documentation at:
https://github.com/center-key/w3c-html-validator#5-ignore-configuration-file

I named the flag `--ignore-config` because `--ignore-file` seemed a bit too easy to confuse with the `--exclude` flag for ignoring files.

I considered a few different JSON structures because JSON is safer than a raw text file, but I just couldn't figure out a JSON structure with comments that I liked more than raw text.  The fact that you can't put real comments in JSON is really annoying.

Anyway, the code is not yet released, and if you have any suggestions for improvements please let me know.  Otherwise, the feature works and is ready to release.

**Comment by pepelsbey** [comment]
I like the `--ignore-config` name :) As for the file format, I think there might be a compromise: YAML. I find the JSON’s lack of comments and strict formatting rules quite annoying to write manually. YAML is much more relaxed and could be easily converted to JSON when needed.

```yaml
# Comment
- Trailing slash on void elements
# Comment
- /^Duplicate ID/
# Comment
- /^Element .blockquote. not allowed/
```

**Comment by pilafmon** [comment]
The config file has been updated to support both strings and regex, like in the above YAML example.  Regex lines now have to be wrapped in slashes, but I think this actually makes the config file easier to read.  Between text, JSON, and YAML for config, none are awesome, but text for a simple list of patterns seems the cleanest.

**Comment by pepelsbey** [comment]
Oh, nice! That was super quick. Thank you for implementing this feature, I’m already using it :)
