### ISSUE TITLE
Validation stopped working after updating w3c-html-validator to version 1.3.3

### ISSUE THREAD

**Issue by Alecto** [center-key/w3c-html-validator#9]
I'm sorry, but I can't figure out the problem that arose after updating to version 1.3.3

I'm checking for version 1.3.2...
![image](https://user-images.githubusercontent.com/8464662/233686396-9bc9a1b8-b6fa-4517-a74b-baf69393abe5.png)

code works
![image](https://user-images.githubusercontent.com/8464662/233686550-885acef9-39b5-4e92-a237-f5af1e0ed3fe.png)

when updating to version 1.3.3 the code stops working
![image](https://user-images.githubusercontent.com/8464662/233686720-004d0815-448c-44e7-9640-1187a4696e46.png)

![image](https://user-images.githubusercontent.com/8464662/233686894-9c44fc0b-f698-4348-9183-a18d2bd76839.png)

It doesn't even get to the file validation, but the problem occurs only after updating the w3cHtmlValidator plugin from version 1.3.2 to version 1.3.3, so I decided to ask you for help.

Just in case, I will add links to the code that I use
https://github.com/Alecto/CodeValidator

Can you suggest an idea where to dig to solve the problem?
Thanks for the help.

**Comment by pilafmon** [comment]
The `glob` library has had some major changes recently.  It looks like your project is picking up the version of `glob` that `w3c-html-validator` just happens to be using.

Since your project directly uses `glob`, it would be best to declare the dependency in your **package.json** file:
```bash
$ npm list glob
$ npm install --save-dev glob
$ npm list glob
```

That way you control which version of `glob` your project uses.  However, I highly recommend updating your code to work with the latest version of `glob`.  You're likely to have recurring problems if you attempt to stick with an old version of `glob`.

**Comment by Alecto** [comment]
yes, you are right. I'll try to solve the problem. thanks for the help!
![image](https://user-images.githubusercontent.com/8464662/233766129-c8cf8db4-fec4-4f1b-8d52-e0e2285e33b1.png)
